[package]
name = "tc_tool"
version = "0.1.0"
authors = ["kotokz <kotokz@live.com>"]

[dependencies]
clap = "*"
glob = "*"
lazy_static = "*"
regex = "*"
time = "*"
clippy = "*"
fnv = "*"

[profile.release]
debug = true
